// Characters
const characters = [
  {
    id: 'char-1',
    name: 'Monkey D. Luffy',
    role: 'Capitão',
    reward: 1500000000,
    fruit: 'Gomu Gomu no Mi',
    affiliation: 'pirata',
    photo: '',
    xp: 3200,
    titles: ['Rei dos Piratas'],
    achievements: ['ach-1'],
    visitedIslands: ['island-1', 'island-3'],
  },
  {
    id: 'char-2',
    name: 'Roronoa Zoro',
    role: 'Espadachim',
    reward: 1110000000,
    fruit: 'Nenhuma',
    affiliation: 'pirata',
    photo: '',
    xp: 2900,
    titles: ['Caçador de Piratas'],
    achievements: ['ach-2'],
    visitedIslands: ['island-2'],
  },
  {
    id: 'char-3',
    name: 'Nami',
    role: 'Navegadora',
    reward: 660000000,
    fruit: 'Nenhuma',
    affiliation: 'pirata',
    photo: '',
    xp: 2200,
    titles: ['Gata dos Céus'],
    achievements: ['ach-3'],
    visitedIslands: ['island-1', 'island-4'],
  },
  {
    id: 'char-4',
    name: 'Trafalgar Law',
    role: 'Médico',
    reward: 900000000,
    fruit: 'Ope Ope no Mi',
    affiliation: 'pirata',
    photo: '',
    xp: 2600,
    titles: ['Cirurgião da Morte'],
    achievements: ['ach-4'],
    visitedIslands: ['island-2', 'island-5'],
  },
  {
    id: 'char-5',
    name: 'Boa Hancock',
    role: 'Imperatriz',
    reward: 550000000,
    fruit: 'Mero Mero no Mi',
    affiliation: 'pirata',
    photo: '',
    xp: 2400,
    titles: ['Imperatriz dos Amazona'],
    achievements: ['ach-5'],
    visitedIslands: ['island-3'],
];

// Achievements
const achievements = [
  {
    id: 'ach-1',
    name: 'Primeira Batalha',
    desc: 'Derrote um inimigo poderoso em combate.',
    xp: 300,
    titleReward: 'Marinheiro Bravo',
    type: 'disponivel',
    icon: '⚔️',
    completedBy: ['char-1'],
  },
  {
    id: 'ach-2',
    name: 'Navegador Sábio',
    desc: 'Navegue por três ilhas diferentes.',
    xp: 250,
    titleReward: 'Vento Cortante',
    type: 'disponivel',
    icon: '🧭',
    completedBy: ['char-3'],
  },
  {
    id: 'ach-3',
    name: 'Conquista Épica',
    desc: 'Derrote um adversário lendário.',
    xp: 500,
    titleReward: 'Herói das Sombras',
    type: 'especial',
    icon: '🌑',
    completedBy: ['char-4'],
  },
  {
    id: 'ach-4',
    name: 'Aliança Secreta',
    desc: 'Forme uma aliança inesperada.',
    xp: 400,
    titleReward: 'Estrategista Sombrio',
    type: 'especial',
    icon: '🗝️',
    completedBy: ['char-2'],
  },
  {
    id: 'ach-5',
    name: 'Tesouro Antigo',
    desc: 'Descubra um tesouro lendário.',
    xp: 350,
    titleReward: 'Caçadora de Relíquias',
    type: 'disponivel',
    icon: '💎',
    completedBy: ['char-5'],
];

// Titles
const titles = [
  {
    id: 'title-1',
    name: 'Rei dos Piratas',
    desc: 'Título concedido ao dono do sonho mais alto.',
    icon: '👑',
    color: '#ffffff',
    req: 'Provar que é o pirata mais livre dos mares.',
  },
  {
    id: 'title-2',
    name: 'Caçador de Piratas',
    desc: 'Fama conquistada com espadas e determinação.',
    icon: '🗡️',
    color: '#dddddd',
    req: 'Vencer duelos consecutivos.',
  },
  {
    id: 'title-3',
    name: 'Gata dos Céus',
    desc: 'A navegadora que lê as nuvens como ninguém.',
    icon: '☁️',
    color: '#eeeeee',
    req: 'Desvendar rotas ocultas.',
  },
  {
    id: 'title-4',
    name: 'Cirurgião da Morte',
    desc: 'Um médico que domina a vida e a morte.',
    icon: '🩺',
    color: '#cccccc',
    req: 'Curar aliados em situações extremas.',
  },
  {
    id: 'title-5',
    name: 'Imperatriz dos Amazona',
    desc: 'Uma líder que impõe respeito absoluto.',
    icon: '🦅',
    color: '#bbbbbb',
    req: 'Proteger seu território com honra.',
];

// Islands
const islands = [
  {
    id: 'island-1',
    name: 'East Blue',
    desc: 'O início da jornada, com céus claros e mares calmos.',
    region: 'East Blue',
    x: 18,
    y: 42,
    type: 'normal',
    visitedBy: ['char-1', 'char-3'],
  },
  {
    id: 'island-2',
    name: 'Grand Line',
    desc: 'A trilha lendária repleta de perigos e relíquias.',
    region: 'Grand Line',
    x: 56,
    y: 48,
    type: 'grandline',
    visitedBy: ['char-2', 'char-4'],
  },
  {
    id: 'island-3',
    name: 'Sabaody',
    desc: 'Arquipélago de bolhas onde nenhum inimigo é seguro.',
    region: 'East Blue',
    x: 32,
    y: 64,
    type: 'special',
    visitedBy: ['char-1', 'char-5'],
  },
  {
    id: 'island-4',
    name: 'Fish-Man Island',
    desc: 'Uma cidade subaquática cheia de mistérios.',
    region: 'Grand Line',
    x: 44,
    y: 28,
    type: 'normal',
    visitedBy: ['char-3'],
  },
  {
    id: 'island-5',
    name: 'Dressrosa',
    desc: 'Uma ilha de fantasia onde o perigo e a festa se misturam.',
    region: 'Grand Line',
    x: 68,
    y: 35,
    type: 'normal',
    visitedBy: ['char-4'],
  },
];
